### ISSUE TITLE
[Bug] Github Actions Pytest: FileNotFoundError

### ISSUE THREAD

**Issue by Schobs** [pykale/pykale#294] opened 2022-01-26 15:42 UTC
# 🐛 Bug

When running the github Actions testing on the [landmark uncertainty branch](https://github.com/pykale/pykale/tree/landmark_uncertainty), my tests fail. I download a zip from github, extract it, and try and access it with pandas during tests. However, when pandas tries to open it, it has a FileNotFound Error. The tests pass on my local machine.

I've logged during tests and confirm the files are downloaded successfully. I have also tried to use the absolute path in the pandas call but still no luck. I have attached the relevant log here, but the full log can be found [here](https://github.com/pykale/pykale/runs/4952932983?check_suite_focus=true).

## To reproduce
Run the Github Actions tests on the landmark_uncertainty pull request. The tests will pass locally but fail on github.

** Stack trace/error message **
```
tests/loaddata/test_tabular_access.py:99: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
kale/loaddata/tabular_access.py:23: in load_csv_columns
    datafame = pd.read_csv(datapath + ".csv", header=0)
/usr/share/miniconda/envs/test/lib/python3.6/site-packages/pandas/io/parsers.py:688: in read_csv
    return _read(filepath_or_buffer, kwds)
/usr/share/miniconda/envs/test/lib/python3.6/site-packages/pandas/io/parsers.py:454: in _read
    parser = TextFileReader(fp_or_buf, **kwds)
/usr/share/miniconda/envs/test/lib/python3.6/site-packages/pandas/io/parsers.py:948: in __init__
    self._make_engine(self.engine)
/usr/share/miniconda/envs/test/lib/python3.6/site-packages/pandas/io/parsers.py:1180: in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
/usr/share/miniconda/envs/test/lib/python3.6/site-packages/pandas/io/parsers.py:2010: in __init__
    self._reader = parsers.TextReader(src, **kwds)
pandas/_libs/parsers.pyx:382: in pandas._libs.parsers.TextReader.__cinit__
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   FileNotFoundError: [Errno 2] No such file or directory: 'tests/test_data/Uncertainty_tuples/PHD-Net/4CH/uncertainty_pairs_test_l0.csv'

pandas/_libs/parsers.pyx:674: FileNotFoundError
----------------------------- Captured stdout call -----------------------------
Downloading https://github.com/pykale/data/raw/main/tabular/cardiac_landmark_uncertainty/Uncertainty_tuples.zip to /home/runner/work/pykale/pykale/tests/test_data/Uncertainty_tuples/Uncertainty_tuples.zip
Extracting /home/runner/work/pykale/pykale/tests/test_data/Uncertainty_tuples/Uncertainty_tuples.zip to /home/runner/work/pykale/pykale/tests/test_data/Uncertainty_tuples
----------------------------- Captured stderr call -----------------------------

0it [00:00, ?it/s]
  0%|          | 0/304435 [00:00<?, ?it/s]
311296it [00:00, 425902.06it/s]           
------------------------------ Captured log call -------------------------------
INFO     root:download.py:49 Downloading and extracting Uncertainty_tuples.zip.
INFO     root:download.py:51 Datasets downloaded and extracted in /home/runner/work/pykale/pykale/tests/test_data/Uncertainty_tuples/Uncertainty_tuples.zip
INFO     test_tabular_access:test_tabular_access.py:79 The file is downloaded and dl to downloaded to:  tests/test_data/Uncertainty_tuples/Uncertainty_tuples.zip 
INFO     test_tabular_access:test_tabular_access.py:83 one step up files:  ['tests/test_data/Uncertainty_tuples/Uncertainty_tuples.zip', 'tests/test_data/Uncertainty_tuples/PHD-NET/4CH/uncertainty_pairs_valid_l1.csv', 'tests/test_data/Uncertainty_tuples/PHD-NET/4CH/uncertainty_pairs_valid_l2.csv', 'tests/test_data/Uncertainty_tuples/PHD-NET/4CH/uncertainty_pairs_test_l1.csv', 'tests/test_data/Uncertainty_tuples/PHD-NET/4CH/uncertainty_pairs_test_l0.csv', 'tests/test_data/Uncertainty_tuples/PHD-NET/4CH/uncertainty_pairs_test_l2.csv', 'tests/test_data/Uncertainty_tuples/PHD-NET/4CH/uncertainty_pairs_valid_l0.csv', 'tests/test_data/Uncertainty_tuples/PHD-NET/SA/uncertainty_pairs_valid_l1.csv', 'tests/test_data/Uncertainty_tuples/PHD-NET/SA/uncertainty_pairs_valid_l2.csv', 'tests/test_data/Uncertainty_tuples/PHD-NET/SA/uncertainty_pairs_test_l1.csv', 'tests/test_data/Uncertainty_tuples/PHD-NET/SA/uncertainty_pairs_test_l0.csv', 'tests/test_data/Uncertainty_tuples/PHD-NET/SA/uncertainty_pairs_test_l2.csv', 'tests/test_data/Uncertainty_tuples/PHD-NET/SA/uncertainty_pairs_valid_l0.csv', 'tests/test_data/Uncertainty_tuples/U-NET/4CH/uncertainty_pairs_valid_l1.csv', 'tests/test_data/Uncertainty_tuples/U-NET/4CH/uncertainty_pairs_valid_l2.csv', 'tests/test_data/Uncertainty_tuples/U-NET/4CH/uncertainty_pairs_test_l1.csv', 'tests/test_data/Uncertainty_tuples/U-NET/4CH/uncertainty_pairs_test_l0.csv', 'tests/test_data/Uncertainty_tuples/U-NET/4CH/uncertainty_pairs_test_l2.csv', 'tests/test_data/Uncertainty_tuples/U-NET/4CH/uncertainty_pairs_valid_l0.csv', 'tests/test_data/Uncertainty_tuples/U-NET/SA/uncertainty_pairs_valid_l1.csv', 'tests/test_data/Uncertainty_tuples/U-NET/SA/uncertainty_pairs_valid_l2.csv', 'tests/test_data/Uncertainty_tuples/U-NET/SA/uncertainty_pairs_test_l1.csv', 'tests/test_data/Uncertainty_tuples/U-NET/SA/uncertainty_pairs_test_l0.csv', 'tests/test_data/Uncertainty_tuples/U-NET/SA/uncertainty_pairs_test_l2.csv', 'tests/test_data/Uncertainty_tuples/U-NET/SA/uncertainty_pairs_valid_l0.csv']
_ test_load_csv_columns_cols_return[return_columns1-PHD-Net/4CH/uncertainty_pairs_test_l0] _

landmark_uncertainty_dl = 'tests/test_data/Uncertainty_tuples'
source_test_file = 'PHD-Net/4CH/uncertainty_pairs_test_l0'
return_columns = ([], [])

    @pytest.mark.parametrize("source_test_file", ["PHD-Net/4CH/uncertainty_pairs_test_l0"])
    @pytest.mark.parametrize(
        "return_columns",
        [
            ("All", EXPECTED_COLS),
            ([], []),
            ("S-MHA Error", ["S-MHA Error"]),
            (["S-MHA Error", "E-MHA Error"], ["S-MHA Error", "E-MHA Error"]),
        ],
    )
    def test_load_csv_columns_cols_return(landmark_uncertainty_dl, source_test_file, return_columns):
    
        # ensure if cols_to_return is "All" that all columns are returned
        # print("LISTING DIR: ", os.listdir(landmark_uncertainty_dl))
        if not os.path.exists(landmark_uncertainty_dl):
            os.makedirs(landmark_uncertainty_dl)
        filename = "Uncertainty_tuples.zip"
        data_path = os.path.join(landmark_uncertainty_dl, filename)
        if not os.path.exists(data_path):
            download_file_by_url(landmark_uncertainty_url, landmark_uncertainty_dl, filename, "zip")
    
            LOGGER.info("The file is downloaded and dl to downloaded to:  %s " % str(data_path))
            # LOGGER.info('The files inside that path:  %s ' % [os.path.join(path, name) for path, subdirs, files in os.walk(data_path) for name in files])
            LOGGER.info(
                "one step up files:  %s "
                % [os.path.join(path, name) for path, subdirs, files in os.walk(landmark_uncertainty_dl) for name in files]
            )
    
        else:
            LOGGER.info("The file already exists: %s " % str(data_path))
            # LOGGER.info('The files inside that path: %s ' % [os.path.join(path, name) for path, subdirs, files in os.walk(data_path) for name in files])
            LOGGER.info(
                "one step up files:  %s "
                % [os.path.join(path, name) for path, subdirs, files in os.walk(landmark_uncertainty_dl) for name in files]
            )
    
        # download_file_by_url(landmark_uncertainty_url, landmark_uncertainty_dl, "Uncertainty_tuples.zip", "zip")
        returned_cols = load_csv_columns(
            (os.path.join(landmark_uncertainty_dl, source_test_file)),
            "Testing Fold",
            np.arange(8),
>           cols_to_return=return_columns[0],
        )

tests/loaddata/test_tabular_access.py:99: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
kale/loaddata/tabular_access.py:23: in load_csv_columns
    datafame = pd.read_csv(datapath + ".csv", header=0)
/usr/share/miniconda/envs/test/lib/python3.6/site-packages/pandas/io/parsers.py:688: in read_csv
    return _read(filepath_or_buffer, kwds)
/usr/share/miniconda/envs/test/lib/python3.6/site-packages/pandas/io/parsers.py:454: in _read
    parser = TextFileReader(fp_or_buf, **kwds)
/usr/share/miniconda/envs/test/lib/python3.6/site-packages/pandas/io/parsers.py:948: in __init__
    self._make_engine(self.engine)
/usr/share/miniconda/envs/test/lib/python3.6/site-packages/pandas/io/parsers.py:1180: in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
/usr/share/miniconda/envs/test/lib/python3.6/site-packages/pandas/io/parsers.py:2010: in __init__
    self._reader = parsers.TextReader(src, **kwds)
pandas/_libs/parsers.pyx:382: in pandas._libs.parsers.TextReader.__cinit__
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   FileNotFoundError: [Errno 2] No such file or directory: 'tests/test_data/Uncertainty_tuples/PHD-Net/4CH/uncertainty_pairs_test_l0.csv'

pandas/_libs/parsers.pyx:674: FileNotFoundError
```

## Expected Behaviour

The file should download and be accessed during the test.
## Environment

N/A. It's the github Actions environment.

## Additional context
I might be missing something obvious here, any help would be appreciated. Thank you.

**Comment by haipinglu** [comment] 2022-01-26 18:03
I provide a different perspective here: For reproducibility, I agree that you need the real data, e.g. in your example. However, for unit testing, do you have to use the real data? See examples in our tests or pytorch etc where random data can be generated for unit tests. You can simply generate some simulated data for the purpose of testing (e.g. random numbers).

**Comment by Schobs** [comment] 2022-01-27 11:44
Sure, for testing the other functions I can do synthetic data. However, this test is testing the load_csv function, so I need a csv file to load

**Comment by haipinglu** [comment] 2022-01-27 11:50
save the synthetic data as csv locally and then load.

**Comment by haipinglu** [comment] 2022-08-11 11:26
@Schobs We are preparing an official release. Could you please update the status or close it and open a new one to reflect the progress so far since it has been 6-month old? Many thanks!

**Comment by Schobs** [comment] 2022-08-11 13:03
Issue resolved in landmark uncertainty branch. Will close this issue.

**Closed** 2022-08-11 13:03 UTC
Labels: bug
